In [2]:
import pandas as pd

In [4]:
# 加载数据集
df = pd.read_excel(r"D:\GitHubRepos\is6400-business-data-analytics\data\cleaned_dataset.xlsx")
df.head(10)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3.0,192000,6,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000,4,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4,Automatic,Front,04-May,Left wheel,Silver,4
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2.0,160931,4,Automatic,Front,04-May,Left wheel,White,4
6,45656768,1803,761,TOYOTA,Prius,2010,Hatchback,Yes,Hybrid,1.8,258909,4,Automatic,Front,04-May,Left wheel,White,12
7,45816158,549,751,HYUNDAI,Sonata,2013,Sedan,Yes,Petrol,2.4,216118,4,Automatic,Front,04-May,Left wheel,Grey,12
8,45641395,1098,394,TOYOTA,Camry,2014,Sedan,Yes,Hybrid,2.5,398069,4,Automatic,Front,04-May,Left wheel,Black,12
9,45756839,26657,-,LEXUS,RX 350,2007,Jeep,Yes,Petrol,3.5,128500,6,Automatic,4x4,04-May,Left wheel,Silver,12

In [6]:
df.describe()

,ID,Price,Prod. year,Engine volume,Mileage,Cylinders,Airbags
count,1.468100e+04,14681.000000,14681.000000,14681.000000,1.468100e+04,14681.000000,14681.000000
mean,4.558740e+07,17729.341939,2011.563381,2.352762,1.097255e+06,4.634902,6.799264
std,8.888501e+05,17822.538641,4.812077,0.901162,4.133381e+07,1.232426,4.347691
min,2.324298e+07,1.000000,1985.000000,0.000000,0.000000e+00,1.000000,0.000000
25%,4.568933e+07,5372.000000,2010.000000,1.800000,7.285700e+04,4.000000,4.000000
50%,4.577290e+07,14069.000000,2012.000000,2.000000,1.289650e+05,4.000000,6.000000
75%,4.580284e+07,23364.000000,2015.000000,2.500000,1.930000e+05,6.000000,12.000000
max,4.581665e+07,194438.000000,2020.000000,20.000000,2.147484e+09,16.000000,16.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14681 entries, 0 to 14680
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                14681 non-null  int64
 1   Price             14681 non-null  int64
 2   Levy              14681 non-null  object
 3   Manufacturer      14681 non-null  object
 4   Model             14681 non-null  object
 5   Prod. year        14681 non-null  int64
 6   Category          14681 non-null  object
 7   Leather interior  14681 non-null  object
 8   Fuel type         14681 non-null  object
 9   Engine volume     14681 non-null  float64
 10  Mileage           14681 non-null  int64
 11  Cylinders         14681 non-null  int64
 12  Gear box type     14681 non-null  object
 13  Drive wheels      14681 non-null  object
 14  Doors             14681 non-null  object
 15  Wheel             14681 non-null  object
 16  Color             14681 non-null  object
 17  Airbags           14681 non-null  int64
dtypes: float64(1), int64(6), object(11)
memory usage: 2.0+ MB